### ISSUE TITLE
no Internet/disconnect check or message before loading balance data

### ISSUE THREAD

**Issue by ChriscomIT** [villers/Coinmonhubpool#3]
Hi,

it's me again. As per title please implement a check for Internet connectivity/error message for no connection (at startup) or when balance data is parsed but no proper Internet connection is available. Overall some check for a proper Internet connection before data is parsed.

I get a catchup error if one of the things mentioned above is valid. It's following: 

> internet disconnect hanled by catch (*_which "**hanled**" is a spelling error indeed_)

> (node:13056) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of > undefined
    at _api2.default.getDataMiningPool.then.then.then.catch.err (C:\Users\chris\AppData\Roaming\npm\node_modules\coinmonhubpool\bin\index.js:40:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:13056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks as always!

**Comment by villers** [comment]
I will add it at the end of my holidays.

**Comment by ChriscomIT** [comment]
Hi, any updates upcoming?

**Comment by villers** [comment]
I'll do it this weekend. :)
